name: Deploy Go Application

on: 
  push: 
    branches: 
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to Docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t iamsachin07/students-api .
      - name: Push image to docker hub
        run: docker push iamsachin07/students-api:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull iamsachin07/students-api:latest
      - name: Delete old container
        run: docker rm -f go-app-container  
      - name: Run docker container          
        run: docker run -d -p 4040:4040 -e PORT=4040 --name go-app-container iamsachin07/students-api
